######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 9 14:09:07 2016
######################################################################

TEMPLATE = lib
TARGET = window.o
DEPENDPATH += .
INCLUDEPATH += .

QT = core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

# Input
HEADERS += window.h
SOURCES += window.cpp
